# Generated by Django 6.0 on 2025-12-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('Roads', 'Roads'), ('Sanitation', 'Sanitation'), ('Electricity', 'Electricity'), ('Water', 'Water'), ('Civic', 'Civic'), ('Health', 'Health'), ('Environment', 'Environment'), ('Education', 'Education'), ('Other', 'Other')], max_length=50),
        ),
    ]
